import hostingerLogo from "@/assets/providers/hostinger-color.svg";

import linodeLogo from "@/assets/providers/linode.svg";
import hetznerLogo from "@/assets/providers/hetzner.svg";

export const PROVIDERS = [
  {
    id: 'hostinger',
    name: 'Hostinger',
    logo: hostingerLogo,
    url: 'https://www.hostinger.com',
    rating: 4.9,
    reviews: 1540,
    price: '$2.99',
    description: 'High-performance shared and cloud hosting with custom hPanel.',
    tag: 'Best for Beginners',
    features: ['Free Domain', 'Free Website Migration', '24/7 Customer Support'],
    pros: ['Extremely Affordable', 'Fast Loading Times', 'User-Friendly Panel'],
    cons: ['Limited Basic Plan', 'No Phone Support'],
    category: 'Shared/Cloud'
  },
  {
    id: 'cloudways',
    name: 'Cloudways',
    logo: '/logo1.png',
    url: 'https://www.cloudways.com',
    rating: 4.8,
    reviews: 980,
    price: '$11.00',
    description: 'Managed cloud hosting platform for developers and agencies.',
    tag: 'Best Managed Cloud',
    features: ['Unlimited Applications', 'Managed Security', 'Free SSL'],
    pros: ['Choice of 5 Clouds', 'Staging Environment', 'Excellent Performance'],
    cons: ['Higher Price Point', 'Learning Curve'],
    category: 'Cloud'
  },
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    logo: 'https://cdn.worldvectorlogo.com/logos/digitalocean-2.svg',
    url: 'https://www.digitalocean.com',
    rating: 4.8,
    reviews: 2100,
    price: '$6.00',
    description: 'Scalable droplets and app platform for modern developers.',
    tag: 'Developer Choice',
    features: ['Kubernetes', 'Managed DBs', 'App Platform'],
    pros: ['Simple Pricing', 'Great Documentation', 'Scalable'],
    cons: ['Support can be slow', 'Complex for total newbies'],
    category: 'VPS/Cloud'
  },
  {
    id: 'vultr',
    name: 'Vultr',
    logo: '/logo4.png',
    url: 'https://www.vultr.com',
    rating: 4.9,
    reviews: 1250,
    price: '$5.00',
    description: 'High-frequency compute with global network presence.',
    tag: 'Highest Performance',
    features: ['Global Network', 'Fast NVMe Storage', 'DDoS Protection'],
    pros: ['Very Fast', 'Low Latency', 'Global Locations'],
    cons: ['Support is ticket-based', 'Strict Terms'],
    category: 'VPS'
  },
  {
    id: 'linode',
    name: 'Linode',
    logo: linodeLogo,
    url: 'https://www.linode.com',
    rating: 4.7,
    reviews: 1100,
    price: '$5.00',
    description: 'Reliable cloud computing by Akamai for all project sizes.',
    tag: 'Rock Solid',
    features: ['Cloud GPU', 'Marketplace', 'Object Storage'],
    pros: ['Reliable Support', 'Stable Platform', 'Great API'],
    cons: ['UI is a bit dated', 'Basic Backups cost extra'],
    category: 'VPS'
  },
  {
    id: 'hetzner',
    name: 'Hetzner',
    logo: hetznerLogo,
    url: 'https://www.hetzner.com',
    rating: 4.8,
    reviews: 850,
    price: '$4.99',
    description: 'Sustainable German hosting with incredible price-to-performance.',
    tag: 'Best Value',
    features: ['AMD EPYC Servers', 'Snapshot Support', 'Unmetered Traffic'],
    pros: ['Incredible Pricing', 'High Performance', 'GDPR Compliant'],
    cons: ['Limited Global Regions', 'Verification Process'],
    category: 'VPS/Dedicated'
  },
  {
    id: 'aws',
    name: 'AWS',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/9/93/Amazon_Web_Services_Logo.svg',
    url: 'https://aws.amazon.com',
    rating: 4.6,
    reviews: 5000,
    price: 'Free Tier',
    description: 'The world\'s most comprehensive and broadly adopted cloud.',
    tag: 'Enterprise Standard',
    features: ['Infinite Scaling', 'Global Regions', 'Massive Ecosystem'],
    pros: ['Unlimited Power', 'Deep Customization', 'Free Tier Available'],
    cons: ['Complex Pricing', 'Steep Learning Curve'],
    category: 'Cloud/Enterprise'
  },
  {
    id: 'google-cloud',
    name: 'Google Cloud',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/51/Google_Cloud_logo.svg',
    url: 'https://cloud.google.com',
    rating: 4.7,
    reviews: 3200,
    price: 'Free Tier',
    description: 'Cloud computing services by Google on world-class infrastructure.',
    tag: 'AI/Data Leader',
    features: ['Compute Engine', 'BigQuery', 'Firebase'],
    pros: ['Fast Network', 'Excellent AI Tools', 'Sustainable'],
    cons: ['Console is complex', 'Customer Support costs extra'],
    category: 'Cloud/Enterprise'
  },
  {
    id: 'bluehost',
    name: 'Bluehost',
    logo: '/logo2.png',
    url: 'https://www.bluehost.com',
    rating: 4.5,
    reviews: 2800,
    price: '$2.95',
    description: 'WordPress recommended hosting with automated setup.',
    tag: 'Best for WordPress',
    features: ['Free Domain', 'Automatic WP Install', '24/7 Chat'],
    pros: ['WP Recommended', 'Easy Setup', 'Affordable Intro'],
    cons: ['High Renewal Rates', 'Aggressive Upsells'],
    category: 'Shared/WP'
  },
  {
    id: 'siteground',
    name: 'SiteGround',
    logo: '/logo3.png',
    url: 'https://www.siteground.com',
    rating: 4.8,
    reviews: 1900,
    price: '$3.99',
    description: 'Premium WordPress hosting with top-tier security and speed.',
    tag: 'Premium WP Hosting',
    features: ['Managed WordPress', 'Daily Backups', 'Free Email'],
    pros: ['Exceptional Support', 'Proprietary Caching', 'Secure'],
    cons: ['Storage is limited', 'Renewals are pricey'],
    category: 'Shared/WP'
  }
];
